# Generated by Django 4.1.7 on 2023-03-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('elec_code', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='electoral code')),
                ('province', models.CharField(max_length=200)),
                ('canton', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('identification', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('voting_board', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=200, verbose_name='name')),
                ('gender', models.CharField(max_length=200)),
                ('id_expiration_date', models.DateTimeField()),
                ('elec_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.location')),
            ],
        ),
    ]
