# Generated by Django 4.1.7 on 2023-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_person_id_expiration_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['province'], name='votes_locat_provinc_1e186e_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['canton'], name='votes_locat_canton_6c90a8_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['district'], name='votes_locat_distric_1a74b4_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['identification', 'elec_code', 'gender'], name='votes_perso_identif_6fae5c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['identification', 'id_expiration_date'], name='votes_perso_identif_5c5032_idx'),
        ),
    ]
